name: "Deploy to Global NuGet"

on:
  push:
    branches:
      - rel/nuget

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  GLOBAL_NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy Release JOB'
    runs-on: 'windows-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: 'Restore Dependencies'
        run: dotnet restore

      - name: 'Build Project'
        run: dotnet build --no-restore --configuration Release

#      - name: 'Test Project'
#        run: dotnet test --no-restore --no-build --configuration Release

      - name: 'Pack Package'
        run: dotnet pack --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.GLOBAL_NUGET_TOKEN }} -s ${{ env.GLOBAL_NUGET_SOURCE_URL }}
